# Default workflow configuration
name: "Default"
description: "Default workflow pattern"
version: 1.0
role: "Default-Workflow Agent"
type: SEQUENTIAL  # all nodes are executed sequentially

# Define nodes in the workflow
nodes:
  - id: DEFINE
    description: "Define the problem scope and objectives"
    
  - id: RESEARCH
    description: "Research relevant information and gather context"
    
  - id: STRATEGIZE
    description: "Develop a strategy to address the problem"
    
  - id: EXECUTE
    description: "Execute the strategy and produce deliverables"
    
  - id: EVALUATE
    description: "Evaluate results and refine as needed"


# Define prompts used in nodes
prompts:
  DEFINE: |
    Define the scope and objectives for:
    {objective}
    
    In your response:
    1. Clearly state the problem to be solved
    2. Define the specific goals and objectives
    3. Identify key stakeholders and their needs
    4. Establish success criteria and constraints
    
  RESEARCH: |
    Based on the problem definition:
    {DEFINE.output}
    
    Research relevant information for:
    {objective}
    
    Your research should:
    1. Identify key facts and background information related to the defined problem
    2. Gather relevant data and evidence needed to address the objectives
    3. Consider different perspectives and viewpoints on the problem
    4. Summarize the most important findings that will inform your strategy
    
  STRATEGIZE: |
    Based on the problem definition:
    {DEFINE.output}
    
    And your research findings:
    {RESEARCH.output}
    
    Develop a comprehensive strategy for:
    {objective}
    
    Your strategy should include:
    1. A high-level approach to solving the problem that addresses the research findings
    2. Key methods and techniques to be employed
    3. Resource requirements and constraints identified in your research
    4. Risk assessment and mitigation plans
    
  EXECUTE: |
    Based on your strategy:
    {STRATEGIZE.output}
    
    Execute your strategy to address:
    {objective}
    
    In your execution:
    1. Apply the methods identified in your strategy
    2. Create necessary deliverables and outputs
    3. Document your process and decisions
    4. Address challenges as they arise
    
  EVALUATE: |
    Based on the original problem definition:
    {DEFINE.output}
    
    And the execution of your strategy:
    {EXECUTE.output}
    
    Evaluate the results of your work on:
    {objective}
    
    Your evaluation should:
    1. Assess how well the objectives were met
    2. Identify strengths and weaknesses in the solution
    3. Suggest refinements or improvements
    4. Provide a final recommendation or conclusion 