#!/usr/bin/env bash


deactivate  # deactive virtual environment if currently in one

python3 -m pip install https://GitHub.com/AI-App/IsDaniel.MCP-Weather-Server/archive/dev.zip \
  --upgrade --user --break-system-packages
