[lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "B",   # bugbear (common Python gotchas)
    "UP",  # pyupgrade (modern Python features)
    "N801", "N803", "N804",  # naming conventions
    "F821", "F822", "F841", "F401",  # undefined names, unused variables/imports
]

ignore = [
    "E203",  # Whitespace before ':' (conflicts with Black)
    "E501",  # Line too long (handled by line-length)
    "B008",  # Function call in default argument
    "B010",  # setattr in class body
    "B904",  # raise ... from ...
    "N802",  # Function name should be lowercase
    "I001",  # import block is un-sorted or un-formatted
    "UP007",  # use `X | Y` for type annotations
]

exclude = [
    "*.na",           # Dana language files
    ".git",           # Version control
    ".venv",          # Virtual environment
    "dana.egg-info",  # Build artifacts
    "__pycache__",    # Python cache
    ".pytest_cache",  # Pytest cache
    ".ruff_cache",    # Ruff cache
]
