site_name: Dana
site_url: https://aitomatic.github.io/dana/
repo_url: https://github.com/aitomatic-oss/dana

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Install: install.md
  - Tech Setup: tech-setup.md
  - Cookbook:
    - Workflows — Multi-Agent Chat: cookbook/workflows_multi_agent_chat.md
    - Workflows — Data Pipeline: cookbook/workflows_data_pipeline.md
    - Workflows — API Orchestration: cookbook/workflows_api_orchestration.md
    - Workflows — Error Recovery: cookbook/workflows_error_recovery.md
  - Concepts: core-concepts.md
  - Primers: primers/agent.md

exclude_docs: |
  .ai-only/
  .archive/
  tmp/
