site_name: Dana
site_url: https://aitomatic.github.io/dana/
repo_url: https://github.com/aitomatic-oss/dana

theme:
  name: material
  features:
    - content.code.copy

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Cookbook:
    - Multi-Agent Chat: cookbook/multi-agent-chat.md
    - Data Pipeline: cookbook/data-pipeline.md
    - API Orchestration: cookbook/api-orchestration.md
    - Error Recovery: cookbook/error-recovery.md
  - Concepts: core-concepts.md
  - Primers: primers/agent.md

exclude_docs: |
  .ai-only/
  .archive/
