[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opendxa"
version = "0.2.0"
description = "Domain-Expert Agent Framework"

[tool.setuptools]
packages = ["opendxa"]

[tool.ruff]
line-length = 140

