[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dxa"
version = "0.1.0"
description = "Domain-Expert Agent Framework"

[tool.setuptools]
packages = ["dxa"]

[tool.ruff]
line-length = 120

