DANA=dana

test-all:
	@ $(DANA) test.na
	@ $(DANA) test-adj-income.na
	@ $(DANA) test-cap-intens.na
	@ $(DANA) test-income-util-ratios.na
	@ $(DANA) test-leverage.na
	@ $(DANA) test-liquidity.na
	@ $(DANA) test-margin-ratios.na
	@ $(DANA) test-return-ratios.na
	@ $(DANA) test-turnover-ratios.na
