// Stub stores for HVAC demo UI
export const useDocumentStore = () => ({
  fetchDocuments: async () => {},
  fetchDocument: async () => {},
  uploadDocument: async () => {},
  updateDocument: async () => {},
  deleteDocument: async () => {},
  downloadDocument: async () => {},
  documents: [],
  selectedDocument: null,
  isLoading: false,
  isUploading: false,
  isUpdating: false,
  isDeleting: false,
  isDownloading: false,
  error: null,
  uploadProgress: 0,
  setSelectedDocument: () => {},
  setUploadProgress: () => {},
  clearError: () => {},
});
