# RF Matching Network Parameters
rf_matching:
  forward_power:
    description: "RF forward power delivered to chamber"
    unit: "watts"
    normal_range: [950, 1050]  # 1000W nominal
    critical_range: [900, 1100]
    sample_rate: "1Hz"

  reflected_power:
    description: "RF power reflected from chamber"
    unit: "watts"
    normal_range: [0, 10]  # <1% reflection normal
    critical_range: [0, 50]
    sample_rate: "1Hz"

  match_position_1:
    description: "Matching network capacitor 1 position"
    unit: "percent"
    normal_range: [40, 60]
    critical_range: [20, 80]
    sample_rate: "1Hz"

  match_position_2:
    description: "Matching network capacitor 2 position"
    unit: "percent"
    normal_range: [45, 55]
    critical_range: [30, 70]
    sample_rate: "1Hz" 