# Default planning configuration
name: default
description: "Default planning pattern"

# Define nodes in the planning process
nodes:
  - id: ANALYZE
    description: "Analyze the problem and break it down into requirements"
    
  - id: DESIGN
    description: "Design a solution architecture and approach"
    
  - id: IMPLEMENT
    description: "Implement the solution according to the design"
    
  - id: VERIFY
    description: "Verify the implementation against requirements"

# Define prompts used in nodes
prompts:
  ANALYZE: |
    Take time to understand the following problem:
    
    {objective}
    
    In your response:
    1. Restate the problem in your own words
    2. Identify what is being asked for
    3. List any assumptions you need to make
    4. Clarify any ambiguous aspects
    
  DESIGN: |
    Design a solution for:
    
    {objective}
    
    In your design:
    1. Break down the solution into components
    2. Define interfaces between components
    3. Specify data structures and algorithms
    4. Consider edge cases and error handling
    
  IMPLEMENT: |
    Implement the solution for:
    
    {objective}
    
    In your implementation:
    1. Write clear, well-documented code
    2. Follow best practices and patterns
    3. Handle errors and edge cases
    4. Include tests where appropriate
    
  VERIFY: |
    Verify the solution for:
    
    {objective}
    
    In your verification:
    1. Test against all requirements
    2. Check for edge cases and errors
    3. Validate performance and scalability
    4. Document any limitations or tradeoffs 