hostname: "0.0.0.0"
port: 3000
servers:
  filesystem:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - "/path/to/root"
  customserver:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-customtype"
