setup-linux:
	@ git pull
	@ .bin/linux-install-dev-tools
	@ .bin/linux-install-python-and-uv
	@ .bin/install-venv-with-dana
	@ .bin/update-git-submodule

setup-mac:
	@ git pull
	@ .bin/mac-install-dev-tools
	@ .bin/mac-install-python-and-uv
	@ .bin/install-venv-with-dana
	@ .bin/update-git-submodule

test-setup:
	@ .bin/test-setup

