"""Domain-Expert Agent (DXA) framework.

DXA is a framework for building domain-expert agents that combine:
- Domain-specific expertise
- LLM-powered reasoning
- Interactive capabilities

Key Components:
- StateManager: Manages agent state and conversation history
- DomainExpertise: Defines areas of expertise and capabilities
- ExpertResource: Implements domain-expert behavior
- ChainOfThoughtReasoning: Provides step-by-step reasoning patterns

Example:
    >>> from opendxa import DomainExpertise, ExpertResource
    >>> expertise = DomainExpertise(
    ...     name="mathematics",
    ...     description="Expert in algebra and calculus",
    ...     capabilities=["equation solving", "differentiation"],
    ...     keywords=["solve", "calculate", "equation"],
    ...     requirements=["mathematical expression"],
    ...     example_queries=["solve x^2 + 2x + 1 = 0"]
    ... )
"""

from .common import (
    DXA_LOGGER,
    get_base_path,
    get_config_path,
    load_agent_config,
    OpenDXAError,
    ConfigurationError,
    LLMError,
    NetworkError,
    WebSocketError,
    ReasoningError,
    AgentError,
    CommunicationError,
    ValidationError,
    StateError,
    BaseIO,
    IOFactory,
    LLMInteractionAnalyzer,
    LLMInteractionVisualizer,
    get_class_by_name,
    BaseState,
    WorldState,
    ExecutionState,
    BaseResource,
    ResourceConfig,
    ResourceResponse,
    ResourceError,
    ResourceUnavailableError,
    LLMResource,
    McpResource,
    BaseMcpService,
    McpEchoService,
    HumanResource,
    WoTResource,
    StdioTransportParams,
    HttpTransportParams,
    Loggable,
    Node,
    Edge,
    NodeType,
    DirectedGraph,
    Cursor,
    TraversalStrategy,
    BreadthFirstTraversal,
    DepthFirstTraversal,
    TopologicalTraversal,
    GraphVisualizer,
    StateManager,
)

from .execution import (
    Workflow,
    WorkflowFactory,
    WorkflowExecutor,
    ExecutionContext,
    Objective,
    ObjectiveStatus,
    ExecutionGraph,
    ExecutionSignal,
    ExecutionSignalType,
    ExecutionNode,
    ExecutionEdge,
    ExecutionNodeStatus,
    PipelineNode,
    Pipeline,
    PipelineFactory,
    PipelineExecutor,
    PipelineContext,
    PipelineStrategy,
    Plan,
    PlanFactory,
    PlanStrategy,
    PlanExecutor,
    Reasoning,
    ReasoningFactory,
    ReasoningStrategy,
    ReasoningExecutor,
    WorkflowStrategy,
    OptimalWorkflowExecutor,
)

from .agent import (
    Agent,
    AgentResource,
    AgentRuntime,
    AgentFactory,
    BaseCapability,
    AgentState,
    ExpertResource,
    ResourceFactory
)

__all__ = [
    # Common
    'DXA_LOGGER',
    'get_base_path',
    'get_config_path',
    'OpenDXAError',
    'ConfigurationError',
    'LLMError',
    'NetworkError',
    'WebSocketError',
    'ReasoningError',
    'AgentError',
    'CommunicationError',
    'ValidationError',
    'StateError',
    'BaseIO',
    'IOFactory',
    'load_agent_config',
    'LLMInteractionAnalyzer',
    'LLMInteractionVisualizer',
    'get_class_by_name',
    'get_base_path',
    'get_config_path',
    'DXA_LOGGER',
    'Loggable',
    'Node',
    'Edge',
    'NodeType',
    'DirectedGraph',
    'Cursor',
    'TraversalStrategy',
    'BreadthFirstTraversal',
    'DepthFirstTraversal', 
    'TopologicalTraversal',
    'GraphVisualizer',
    'BaseState',
    'WorldState',
    'ExecutionState',
    'StateManager',
    'BaseResource',
    'ResourceConfig',
    'ResourceResponse',
    'ResourceError',
    'ResourceUnavailableError',
    'LLMResource',
    'McpResource',
    'BaseMcpService',
    'McpEchoService',
    'HumanResource',
    'WoTResource',
    'StdioTransportParams',
    'HttpTransportParams',

    # Agent
    'Agent',
    'AgentResource',
    'AgentRuntime',
    'AgentFactory',
    'BaseCapability',
    'AgentState',
    'ExpertResource',   
    "ResourceFactory",

    # Execution
    "Workflow",
    "WorkflowFactory",
    "WorkflowExecutor",
    "ExecutionContext",
    "Objective",
    "ObjectiveStatus",
    "ExecutionGraph",
    "ExecutionSignal",
    "ExecutionSignalType",
    "ExecutionNode",
    "ExecutionEdge",
    'ExecutionNodeStatus',
    'ExecutionContext',
    'PipelineNode',
    'Workflow',
    'WorkflowFactory',
    'WorkflowExecutor',
    'OptimalWorkflowExecutor',
    'WorkflowStrategy',
    'Pipeline',
    'PipelineFactory',
    'PipelineExecutor',
    'PipelineContext',
    'PipelineStrategy',
    'Plan',
    'PlanFactory',
    'PlanStrategy',
    'PlanExecutor',
    'Reasoning',
    'ReasoningFactory',
    'ReasoningStrategy',
    'ReasoningExecutor',
]