"""Update knowledge_packs, Add interview_templates and interview_sessions

Revision ID: 695b54fda534
Revises: 887dabc61bbc
Create Date: 2025-10-11 19:22:57.911060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "695b54fda534"
down_revision: Union[str, Sequence[str], None] = "887dabc61bbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interview_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("kp_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("folder_path", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_master", sa.Boolean(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["kp_id"],
            ["knowledge_packs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_interview_templates_id"), "interview_templates", ["id"], unique=False)
    op.create_index(op.f("ix_interview_templates_kp_id"), "interview_templates", ["kp_id"], unique=False)
    op.create_index(op.f("ix_interview_templates_name"), "interview_templates", ["name"], unique=False)
    op.create_table(
        "interview_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("interview_template_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=True),
        sa.Column("session_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("interviewee_name", sa.String(), nullable=True),
        sa.Column("interviewee_role", sa.String(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations_v2.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interview_template_id"],
            ["interview_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("rm"), "interview_sessions", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_interview_sessions_id"), "interview_sessions", ["id"], unique=False)
    op.create_index(op.f("ix_interview_sessions_interview_template_id"), "interview_sessions", ["interview_template_id"], unique=False)

    # Use batch operations for SQLite compatibility
    with op.batch_alter_table("knowledge_packs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("status", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("generation_task_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_knowledge_packs_generation_task_id", "background_tasks", ["generation_task_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch operations for SQLite compatibility
    with op.batch_alter_table("knowledge_packs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_knowledge_packs_generation_task_id", type_="foreignkey")
        batch_op.drop_column("generation_task_id")
        batch_op.drop_column("status")

    op.drop_index(op.f("ix_interview_sessions_interview_template_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_id"), table_name="interview_sessions")
    op.drop_index(op.f("ix_interview_sessions_conversation_id"), table_name="interview_sessions")
    op.drop_table("interview_sessions")
    op.drop_index(op.f("ix_interview_templates_name"), table_name="interview_templates")
    op.drop_index(op.f("ix_interview_templates_kp_id"), table_name="interview_templates")
    op.drop_index(op.f("ix_interview_templates_id"), table_name="interview_templates")
    op.drop_table("interview_templates")
    # ### end Alembic commands ###
