"""Add folder path to interview_sessions

Revision ID: c7cd1ef038b1
Revises: d31ca374ba28
Create Date: 2025-10-15 14:32:19.839283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c7cd1ef038b1"
down_revision: Union[str, Sequence[str], None] = "d31ca374ba28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations_v2", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_conversations_v2_template_id", "interview_templates", ["template_id"], ["id"])
        batch_op.create_foreign_key("fk_conversations_v2_session_id", "interview_sessions", ["session_id"], ["id"])
    op.add_column("interview_sessions", sa.Column("folder_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations_v2", schema=None) as batch_op:
        batch_op.drop_constraint("fk_conversations_v2_template_id", type_="foreignkey")
        batch_op.drop_constraint("fk_conversations_v2_session_id", type_="foreignkey")
    op.drop_column("interview_sessions", "folder_path")
    # ### end Alembic commands ###
