# GitHub Action to run pytest sequentially (for comprehensive testing)
# - Runs on Python 3.12
# - Installs the package and its dependencies
# - Tests struct implementation comprehensively with mock LLM
# - Executes fast regression tests only (excludes deep/comprehensive tests)
# - For parallel testing (faster CI), use pytest-parallel.yml instead
# - For full test coverage, run locally with: uv run pytest -m "not live" tests/
# This helps catch regressions quickly while keeping CI times reasonable

name: PyTest Sequential

on: 
  push:
    branches: [main, master]  # Only run on main branch pushes

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v6
    - name: Install dependencies
      run: uv sync --extra dev
    - name: Test struct implementation (comprehensive)
      env:
        OPENDXA_MOCK_LLM: "true"
        OPENDXA_USE_REAL_LLM: "false"
        PYTHONPATH: ${{ github.workspace }}
      run: uv run pytest tests/dana/sandbox/interpreter/test_struct_* -v --tb=short
    - name: Test POET framework (comprehensive)
      env:
        OPENDXA_MOCK_LLM: "true"
        OPENDXA_USE_REAL_LLM: "false"
        PYTHONPATH: ${{ github.workspace }}
      run: uv run pytest tests/dana/poet/ -m "poet" -v --tb=short
    - name: Test with pytest (fast tests only)
      env:
        OPENDXA_MOCK_LLM: "true"
        OPENDXA_USE_REAL_LLM: "false"
        PYTHONPATH: ${{ github.workspace }}
      run: uv run pytest -m "not live and not deep" tests/ --tb=short -v
