# GitHub Action to run pytest on pull requests
# - Runs on Python 3.12
# - Installs the package and its dependencies
# - Executes all tests in the tests/ directory
# This helps catch test failures before merging PRs

name: PyTest

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev,viz]"
    - name: Test with pytest
      run: |
        pytest tests/ --import-mode=importlib
